# В нашей автоматизации список из четырех задач
---
- name: init artifact
  become: true
  maven_artifact:
    dest: "/opt/sausage-store/backend/lib/sausage-store.jar"
    repository_url: "https://nexus.praktikum-services.ru/service/rest/repository/browse/sausage-store-komarov-artur-backend"
    group_id: "com.yandex.practicum.devops"
    artifact_id: "sausage-store-backend"
    version: "sausage-store-1.0.214567.jar"
    username: "a.komarov"
    password: "E]3rX2#y"

- name: Add service user
  become: true
  user:
    name: "jarservice"
    create_home: no
    shell: /sbin/nologin

- name: change permission sausage-store-backend
  become: true
  ansible.builtin.file:
    path: "/opt/sausage-store/backend/lib/sausage-store.jar"
    owner: jarservice
    group: jarservice
    mode: "750"

- name: template config systemd
  become: true
  template:
    src: sausage-store-backend.service.j2
    dest: /etc/systemd/system/sausage-store-backend.service

- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: systemd up service
  become: true
  ansible.builtin.service:
    name: sausage-store-backend
    enabled: yes

- name: startuem
  become: true
  service:
    name: sausage-store-backend
    state: restarted
